[phases.setup]
nixPkgs = ["frankenphp", "php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.fileinfo", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "frankenphp run --config /app/Caddyfile"